export const reducerCases = {
    SET_EVENT_LIST: "SET_EVENT_LIST",
    SET_EVENT_DETAILS: "SET_EVENT_DETAILS",
    SET_UPCOMING_EVENT: "SET_UPCOMING_EVENT",
    SET_TESTIMONIALS: "SET_TESTIMONIALS",
    SET_MEMBERS: "SET_MEMBERS",
    SET_NOTIFICATION: "SET_NOTIFICATION",
};